server:
  port: 0

spring:
  application:
    name: company-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/crm_realm

  data:
    mongodb:
      host: localhost
      port: 27017
      database: companydb

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone:
        - http://localhost:8761/eureka/
logging:
  level:
    web: debug
  file:
    name: ./log/company-service